localhost: &default
  host: <%= ENV['IMAP_HOST'] %>
  port: <%= ENV['IMAP_PORT'] %>
  username: <%= ENV['IMAP_USERNAME'] %>
  password: <%= ENV['IMAP_PASSWORD'] %>

ruby-dev:
  <<: *default

ruby-core:
  <<: *default
